### ISSUE TITLE
Can't expand error in quick-fix window

### ISSUE THREAD

**Issue by Alechan** [JarrodCTaylor/vim-python-test-runner#20]
Very nice plugin, but found an inconvenience when showing errors.
 
Sometimes it's necessary to view more than the Error, just as it's execution stack. I can't figure out how to expand the error to show the execution stack that triggered the error.

Example:
Without the stack, the error makes it ambiguos because it seams that the "rows" triggering the error is the one in the test and not the one in the original class.

Inside vim:
![Without Stack](http://i.imgur.com/whPdOU2.png)

In the console:
![With Stack](http://i.imgur.com/bqCn2mn.png)

**Comment by JarrodCTaylor** [comment]
The info populated in the quickfix window is dictated by [this line](https://github.com/JarrodCTaylor/vim-python-test-runner/blob/master/autoload/vim_python_test_runner.vim#L2) 

If you do a `:h errorformat` you can read vim's help docs about how to change it to suit your needs.

**Comment by Alechan** [comment]
For anyone in the future, a "quick fix for the quickfix" would be to just comment the line indicated by JarrodCTaylor and you'll avoid to deal with that chunk of intelligible characters (assuming you have 0 experience with that sort of parsing, like I do)
