### ISSUE TITLE
Incorrect path in vim_python_test_runner_cache

### ISSUE THREAD

**Issue by khornberg** [JarrodCTaylor/vim-python-test-runner#27]
I have the following config in an `egg`: `{"app_name": "apps", "test-runner": "django"}`

When starting the test with `<Leader>dm` the path to the test is `apps.client.client1.tests.client1_tests.ClientTests.test_client_receives_201_when_posting_with_correct_data`

the correct path is with a colon between the file name and the class name  `apps.client.client1.tests.client1_tests:ClientTests.test_client_receives_201_when_posting_with_correct_data`

Using `<Leader>df` runs the file fine in the project.

**Comment by JarrodCTaylor** [comment]
Are you setting up your `.vim-django` file in this manner? https://github.com/JarrodCTaylor/vim-python-test-runner#vim-django-config-file-example-for-namespace-packages

**Comment by khornberg** [comment]
No. I just realized that.
