### ISSUE TITLE
Nose runner errs with `python: can't open file ':nosetests':` and then creates file in test directory

### ISSUE THREAD

**Issue by voidnologo** [JarrodCTaylor/vim-python-test-runner#29]
Mac OS X 10.13
Python 3.6.2
Python 3.4.4
Python 2.7.10
nose==1.3.0 and nose==1.3.7[latest on pypi]
Latest JarrodCTaylor dotfiles install

I am using `nm` to run a python unittest method.  The test runs correctly (gets proper ERROR/FAIL/OK status) and displays the usual `Press ENTER or type command to continue`.  It then displays an error `python: can't open file ':nosetests': [Errno 2] No such file or directory` and creates a file in the test directory with the file name of the `{test py file}:{test class}.{method name}`  (ex: `test_x.py:XTests.test_x`) that has the contents of the mentioned error message .  

I have tried to debug through the test runner to see where the error is happening, but cannot find it.  

Could you help point me in the right direction to figure out what is happening here?

-  This happens for both `nm` and `nc`
-  For `nf` it does not create a new file, but overwrites the contents of the test file with the error message.
-  This does not happen when running `nosetests` from the cmd line.
-  Error also happened when I did not have nose installed in the virtualenv

![image](https://user-images.githubusercontent.com/7006259/34067151-51bfe762-e1e3-11e7-857d-ce86f170fcc8.png)

![image](https://user-images.githubusercontent.com/7006259/34067153-609f547a-e1e3-11e7-9f3b-1209ca234dfb.png)

Virtualenv without nose installed:
![image](https://user-images.githubusercontent.com/7006259/34067194-32b1fcb0-e1e4-11e7-9519-b84361883b43.png)

**Comment by JarrodCTaylor** [comment]
Is this always an issue or just for a specific project? Do you have an example repo I can take a look at?

**Comment by JacobDawson98** [comment]
I have this issue too on https://github.com/JacobDawson98/screenshot_twitterbot
